name: trains
description: Trains schedule

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  http: ^0.12.0+2
  intl: ^0.16.0
  rxdart: ^0.22.6
  flutter_svg: ^0.15.0
  sliding_up_panel: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  flutter_launcher_name: "^0.0.1"
  
flutter_launcher_name:
  name: "Электрички"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon-ios.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"

flutter:
  
  assets:
  - assets/transitLines/m1.svg
  - assets/transitLines/m5.svg
  - assets/transitLines/m9.svg
  - assets/transitLines/m10.svg
  - assets/transitLines/m14-back.svg
  - assets/transitLines/m14-fore.svg
  - assets/transitLines/ka.svg
  - assets/transitLines/ku.svg
  - assets/transitLines/ya.svg
  - assets/trainClasses/express.svg
  - assets/trainClasses/express-de.svg
  - assets/trainClasses/standart.svg
  - assets/trainClasses/standart-de.svg
  - assets/trainClasses/comfort.svg
  - assets/trainClasses/comfort-de.svg
  - assets/trainClasses/d2.svg
  - assets/trainClasses/d2-de.svg
  - assets/trainClasses/d3.svg
  - assets/trainClasses/d3-de.svg

  fonts:
  - family: Moscow Sans
    fonts:
      - asset: fonts/Moscow Sans/Moscow Sans.ttf
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
      - asset: fonts/Montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: fonts/Montserrat/Montserrat-Bold.ttf
        weight: 700
  - family: PT Root UI
    fonts:
      - asset: fonts/PT Root UI/PT Root UI-Light.ttf
        weight: 300
      - asset: fonts/PT Root UI/PT Root UI-Regular.ttf
      - asset: fonts/PT Root UI/PT Root UI-Medium.ttf
        weight: 500
      - asset: fonts/PT Root UI/PT Root UI-Bold.ttf
        weight: 700
  
  uses-material-design: true
