name: trains
description: Trains schedule

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  intl: ^0.16.0
  rxdart: ^0.22.6
  auto_size_text: ^2.1.0
  cloud_firestore: 0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  flutter_launcher_name: "^0.0.1"
  
flutter_launcher_name:
  name: "Электрички"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icons/icon.png"
  image_path_ios: "assets/app_icons/icon-ios.png"
  adaptive_icon_background: "assets/app_icons/background.png"
  adaptive_icon_foreground: "assets/app_icons/foreground.png"

flutter:
  uses-material-design: true

  assets:
  - assets/map_style_dark.json
  - assets/types/m1.png
  - assets/types/m5.png
  - assets/types/m9.png
  - assets/types/m10.png
  - assets/types/m14.png
  - assets/types/ka.png
  - assets/types/ku.png
  - assets/types/ya.png
  - assets/types/ex.png
  - assets/types/st.png
  - assets/types/cm.png
  - assets/types/d2.png
  - assets/types/d3.png
  - assets/maps/s2006004.png
  - assets/maps/s9600212.png
  - assets/maps/s9602944.png
  - assets/maps/s9603256.png
  - assets/maps/s9603256.png
  - assets/maps/s9603256.png
  - assets/maps/s9603468.png
  - assets/icons/bidirectional_arrow-primary.png
  - assets/icons/bidirectional_arrow-secondary.png
  - assets/icons/bookmarks-primary.png
  - assets/icons/bookmarks-secondary.png
  - assets/icons/group-primary.png
  - assets/icons/group-secondary.png

  fonts:
  - family: Moscow Sans
    fonts:
      - asset: fonts/Moscow Sans/Moscow Sans.ttf
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
      - asset: fonts/Montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: fonts/Montserrat/Montserrat-Bold.ttf
        weight: 700
  - family: PT Root UI
    fonts:
      - asset: fonts/PT Root UI/PT Root UI-Light.ttf
        weight: 300
      - asset: fonts/PT Root UI/PT Root UI-Regular.ttf
      - asset: fonts/PT Root UI/PT Root UI-Medium.ttf
        weight: 500
      - asset: fonts/PT Root UI/PT Root UI-Bold.ttf
        weight: 700